import { Component, OnInit } from "@angular/core";
import { DynamicDialogRef, DynamicDialogConfig } from "primeng/dynamicdialog";
import { OptionsOrderBuilderService } from "../../strategies/options-order-builder.service";
import { AutopilotService, SwingtradeAlgorithms } from "../autopilot.service";
import { SmartOrder } from "@shared/index";

@Component({
  selector: "app-strategy-finder-dialog",
  templateUrl: "./strategy-finder-dialog.component.html",
  styleUrls: ["./strategy-finder-dialog.component.scss"],
})
export class StrategyFinderDialogComponent implements OnInit {
  tradingPairs: SmartOrder[][] = [];
  value = 1;

  // results generated by onSelectChange when user picks "Create Strategy"
  signalResults: Array<{
    signal: string;
    buys: Array<{ symbol: string; movement: any }>;
    sells: Array<{ symbol: string; movement: any }>;
  }> = [];

  savedStrategies: any[] = [
    { name: "Intraday Strategies", value: 1 },
    { name: "All Strategies", value: 2 },
    { name: "Create Strategy", value: 3 },
  ];

  constructor(
    public ref: DynamicDialogRef,
    public config: DynamicDialogConfig,
    private optionsOrderBuilderService: OptionsOrderBuilderService,
    public autopilotService: AutopilotService,
  ) {}

  ngOnInit(): void {
    if (this.config && this.config.data && this.config.data.tradingPairs) {
      this.tradingPairs = this.config.data.tradingPairs;
    } else {
      this.tradingPairs = this.optionsOrderBuilderService.getTradingPairs();
    }
  }

  close() {
    this.ref.close();
  }

  async onSelectChange(event) {
    // Handle selection change if needed
    console.log("Selected strategy value:", event);
    if (event.value === 3) {
      // 1. Get backtest data
      const savedBacktest = JSON.parse(
        localStorage.getItem("backtest") || "{}",
      );

      // Helper to format/find movement
      const getMovement = (symbol: string) => {
        // Find the entry that matches this symbol in savedBacktest
        const match = Object.values(savedBacktest).find(
          (b: any) => b.stock === symbol,
        );
        return match ? (match as any).impliedMovement : null;
      };
      const signals = [
        SwingtradeAlgorithms.mfi,
        SwingtradeAlgorithms.mfiTrade,
        SwingtradeAlgorithms.flagPennant,
        SwingtradeAlgorithms.mfiDivergence,
        SwingtradeAlgorithms.mfiDivergence2,
        SwingtradeAlgorithms.breakResistance,
        SwingtradeAlgorithms.breakSupport,
        SwingtradeAlgorithms.bbandBreakout,
        SwingtradeAlgorithms.mfiLow,
        SwingtradeAlgorithms.macd,
        SwingtradeAlgorithms.roc,
      ];

      // Helper function to map strings to objects with movement data
      const mapWithMovement = (arr: string[]) =>
        arr.map((symbol) => ({
          symbol,
          movement: getMovement(symbol),
        }));

      // collect results from all signals
      this.signalResults = [];
      for (const sig of signals) {
        const result = this.autopilotService.addPairOnSignal(sig, "buy", false);
        this.signalResults.push({
          signal: sig,
          buys: mapWithMovement(result.buys),
          sells: mapWithMovement(result.sells),
        });
      }

      for (const oppositeSig of signals) {
        const result = this.autopilotService.addPairOnSignal(
          oppositeSig,
          "sell",
          false,
        );
        this.signalResults.push({
          signal: oppositeSig + " (sell)",
          buys: mapWithMovement(result.buys),
          sells: mapWithMovement(result.sells),
        });
      }

      console.log("all signal results", this.signalResults);

      // attempt to balance trades for all signals that have both buys and sells
      for (const sr of this.signalResults) {
        if (sr.buys.length && sr.sells.length) {
          const result = await this.optionsOrderBuilderService.balanceTrades(
            sr.buys.map(item => item.symbol),
            sr.sells.map(item => item.symbol),
            1000,
            5000,
            `Signal-generated pair (${sr.signal})`,
          );
          console.log(`balanceTrades returned for ${sr.signal}`, result);
        }
      }
    }
  }
}
