import { Component, OnInit } from '@angular/core';
import { DynamicDialogRef, DynamicDialogConfig } from 'primeng/dynamicdialog';
import { OptionsOrderBuilderService } from '../../strategies/options-order-builder.service';
import { AutopilotService, SwingtradeAlgorithms } from '../autopilot.service';
import { SmartOrder } from '@shared/index';

@Component({
  selector: 'app-strategy-finder-dialog',
  templateUrl: './strategy-finder-dialog.component.html',
  styleUrls: ['./strategy-finder-dialog.component.scss']
})
export class StrategyFinderDialogComponent implements OnInit {
  tradingPairs: SmartOrder[][] = [];
  value = 1;

  // results generated by onSelectChange when user picks "Create Strategy"
  buys: string[] = [];
  sells: string[] = [];
  selectedSignal: string | null = null;
  
  savedStrategies: any[] = [
      { name: 'Intraday Strategies', value: 1 },
      { name: 'All Strategies', value: 2 },
      { name: 'Create Strategy', value: 3 }
  ];

  constructor(
    public ref: DynamicDialogRef,
    public config: DynamicDialogConfig,
    private optionsOrderBuilderService: OptionsOrderBuilderService,
    public autopilotService: AutopilotService
  ) { }

  ngOnInit(): void {
    if (this.config && this.config.data && this.config.data.tradingPairs) {
      this.tradingPairs = this.config.data.tradingPairs;
    } else {
      this.tradingPairs = this.optionsOrderBuilderService.getTradingPairs();
    }
  }

  close() {
    this.ref.close();
  }

  async onSelectChange(event) {
    // Handle selection change if needed
    console.log('Selected strategy value:', event);
    if (event.value === 3) {
      const signals = [
        SwingtradeAlgorithms.mfi,
        SwingtradeAlgorithms.mfiTrade,
        SwingtradeAlgorithms.breakResistance,
        SwingtradeAlgorithms.breakSupport,
        SwingtradeAlgorithms.flagPennant,
        SwingtradeAlgorithms.mfiDivergence,
        SwingtradeAlgorithms.mfiDivergence2
      ];
      // iterate through signal types until we generate both buys and sells
      let buys: string[] = [];
      let sells: string[] = [];
      let foundSignal: string | null = null;
      for (const sig of signals) {
        const result = this.autopilotService.addPairOnSignal(sig, 'buy', false);
        buys = result.buys;
        sells = result.sells;
        if (buys.length && sells.length) {
          foundSignal = sig;
          break;
        }
      }
      console.log('selected signal result', { buys, sells, signal: foundSignal });
      // store the arrays for template display
      this.buys = buys;
      this.sells = sells;
      this.selectedSignal = foundSignal;
      if (buys.length && sells.length) {
        // allocate fixed cash amounts for testing
        const result = await this.optionsOrderBuilderService.balanceTrades(buys, sells, 1000, 5000, 'Signal-generated pair');
        console.log('balanceTrades returned', result);
      }
    }
  }
}
