import { Component, OnInit } from "@angular/core";
import { DynamicDialogRef, DynamicDialogConfig } from "primeng/dynamicdialog";
import { OptionsOrderBuilderService } from "../../strategies/options-order-builder.service";
import { AutopilotService, SwingtradeAlgorithms } from "../autopilot.service";
import { SmartOrder } from "@shared/index";

interface SignalResult {
  signal: string;
  buys: Array<{ symbol: string; movement: any }>;
  sells: Array<{ symbol: string; movement: any }>;
  generatedAt?: number;
}

@Component({
  selector: "app-strategy-finder-dialog",
  templateUrl: "./strategy-finder-dialog.component.html",
  styleUrls: ["./strategy-finder-dialog.component.scss"],
})
export class StrategyFinderDialogComponent implements OnInit {
  tradingPairs: SmartOrder[][] = [];
  value = 1;
  private readonly signalResultsStorageKey = "signalGeneratedPairs";
  private readonly backtestStorageKey = "backtest";

  // results generated by onSelectChange when user picks "Create Strategy"
  signalResults: SignalResult[] = [];

  savedStrategies: any[] = [
    { name: "Intraday Strategies", value: 1 },
    { name: "All Strategies", value: 2 },
    { name: "Create Strategy", value: 3 },
  ];

  constructor(
    public ref: DynamicDialogRef,
    public config: DynamicDialogConfig,
    private optionsOrderBuilderService: OptionsOrderBuilderService,
    public autopilotService: AutopilotService,
  ) {}

  ngOnInit(): void {
    if (this.config && this.config.data && this.config.data.tradingPairs) {
      this.tradingPairs = this.config.data.tradingPairs;
    } else {
      this.tradingPairs = this.optionsOrderBuilderService.getTradingPairs();
    }

    this.signalResults = this.getSavedSignalResults();
  }

  private getSavedSignalResults(): SignalResult[] {
    const raw = localStorage.getItem(this.signalResultsStorageKey);
    if (!raw) {
      return [];
    }

    try {
      const parsed = JSON.parse(raw) as SignalResult[];
      const pruned = this.pruneSavedSignalResults(parsed);
      localStorage.setItem(
        this.signalResultsStorageKey,
        JSON.stringify(pruned),
      );
      return pruned;
    } catch (error) {
      console.warn("Unable to parse saved signal results", error);
      localStorage.removeItem(this.signalResultsStorageKey);
      return [];
    }
  }

  private pruneSavedSignalResults(results: SignalResult[]): SignalResult[] {
    const cutoff = Date.now() - 2 * 24 * 60 * 60 * 1000;
    return (results || []).filter(
      (result) => result.generatedAt && result.generatedAt >= cutoff,
    );
  }

  private saveSignalResults(results: SignalResult[]): void {
    const previous = this.getSavedSignalResults();
    const merged = [
      ...previous,
      ...results.map((result) => ({ ...result, generatedAt: Date.now() })),
    ];
    localStorage.setItem(
      this.signalResultsStorageKey,
      JSON.stringify(this.pruneSavedSignalResults(merged)),
    );
  }

  close() {
    this.ref.close();
  }

  async onSelectChange(event: { value: number }) {
    // Handle selection change if needed
    console.log("Selected strategy value:", event);
    if (event.value === 3) {
      const savedBacktest = JSON.parse(
        localStorage.getItem(this.backtestStorageKey) || "{}",
      );

      const backtestMap = new Map<string, any>();
      Object.values(savedBacktest).forEach((b: any) => {
        if (b && b.stock) {
          backtestMap.set(b.stock, b.impliedMovement);
        }
      });

      const getMovement = (symbol: string) => backtestMap.get(symbol) || null;
      const signals = [
        SwingtradeAlgorithms.mfi,
        SwingtradeAlgorithms.mfiTrade,
        SwingtradeAlgorithms.flagPennant,
        SwingtradeAlgorithms.mfiDivergence,
        SwingtradeAlgorithms.mfiDivergence2,
        SwingtradeAlgorithms.breakResistance,
        SwingtradeAlgorithms.breakSupport,
        SwingtradeAlgorithms.bbandBreakout,
        SwingtradeAlgorithms.mfiLow,
        SwingtradeAlgorithms.macd,
        SwingtradeAlgorithms.roc,
      ];

      // Helper function to map strings to objects with movement data
      const mapWithMovement = (arr: string[]) =>
        arr.map((symbol) => ({
          symbol,
          movement: getMovement(symbol),
        }));

      const existing = [...this.signalResults]; // keep what was loaded from localStorage
      const newResults: SignalResult[] = [];
      for (const sig of signals) {
        const result = this.autopilotService.addPairOnSignal(sig, "buy", false);
        newResults.push({
          signal: sig,
          buys: mapWithMovement(result.buys),
          sells: mapWithMovement(result.sells),
        });
      }

      for (const oppositeSig of signals) {
        const result = this.autopilotService.addPairOnSignal(
          oppositeSig,
          "sell",
          false,
        );
        newResults.push({
          signal: oppositeSig + " (sell)",
          buys: mapWithMovement(result.buys),
          sells: mapWithMovement(result.sells),
        });
      }

      const filtered = newResults.filter(
        (sr) => sr.buys?.length || sr.sells?.length,
      );

      if (filtered.length) {
        this.saveSignalResults(filtered);
      }

      this.signalResults = [...existing, ...filtered];
      console.log("all signal results", this.signalResults);

      // attempt to balance trades for all signals that have both buys and sells
      for (const sr of this.signalResults) {
        if (sr.buys.length && sr.sells.length) {
          const result = await this.optionsOrderBuilderService.balanceTrades(
            sr.buys.map((item) => item.symbol),
            sr.sells.map((item) => item.symbol),
            1000,
            5000,
            `Signal-generated pair (${sr.signal})`,
          );
          console.log(`balanceTrades returned for ${sr.signal}`, result);
        }
      }
    }
  }
}
